### ISSUE TITLE
read-int.ck is broken

### ISSUE THREAD

**Issue by terryzfeng** [ccrma/webchuck-ide#39]
When trying to fetch the text file, there seems to be a text buffer issue. 

```
chunk-DMIQUYQW.js?v=20628a86:41030 Uncaught (in promise) TypeError: factory.create is not a function
    at createTextBuffer (chunk-DMIQUYQW.js?v=20628a86:41030:18)
    at TextModel2.setValue (chunk-DMIQUYQW.js?v=20628a86:41287:44)
    at StandaloneEditor2.setValue (chunk-DMIQUYQW.js?v=20628a86:50061:31)
    at Editor.setEditorCode (editor.ts:203:23)
    at ProjectFile.loadFile (projectFile.ts:31:20)
    at ProjectSystem.setActiveFile (projectSystem.ts:118:38)
    at ProjectSystem.addNewFile (projectSystem.ts:105:27)
    at moreExamples.ts:372:27
```

**Comment by terryzfeng** [comment]
This is now currently fixed on the dev branch, awaiting release (v2.1.5)
